#cs ----------------------------------------
 This file has been generated by
 T-RECORDER version: ${version}
 ${date}
 IVQ engineer :
 SAT/NMS/NMS-L

 DESCRIPTION :

 Profile 0: Empty
 Profile 1: Empty
 Profile 2: Empty
 Profile 3: Empty
 Profile 4: Empty
 Profile 5: Empty
 Profile 6: Empty
 Profile 7: Empty
 Profile 8: Empty
 Profile 9: Empty
#ce -----------------------------------------

Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
